---
title: "Correlations"
author: "Francisko de Moraes Rezende"
date: "3/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Running correlations for Gui

## Setup

### Loading packages

```{r loading-pkgs}
list_of_packages <- c("tidyverse", "readxl", "here")
new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)

library(tidyverse)
library(readxl)
library(here)
```

### Loading data

```{r loading-data}
data_path <- 
  here::here("data")


files <- 
  dir(path = data_path,
      pattern = "*.xls|*.xlsx")

adsorbed_particles <-
files %>% 
  purrr::map(~ readxl::read_excel(file.path(data_path, .))) %>%
  purrr::set_names(nm = c("particle_count",
                          "macro",
                          "micro",
                          "wetability",
                          "celular_perimeter",
                          "ui"
                          ))
```

### Standardising the sheets

```{r}
adsorbed_particles %>% 
  purrr::pluck("particle_count") %>% 
  dplyr::rename(sp = Sp,
                face = Face,
                frag = Frag,
                site = Site) %>% 
  dplyr::mutate(
    site = dplyr::case_when(
    site == "BR" ~ 1,
    site == "CA" ~ 2,
    site == "VZ" ~ 3,
    site == "CN" ~ 4,
    site == "REF" ~ 5),
    `<2.5` = as.numeric(`<2.5`),
    `2.5-10` = as.numeric(`2.5-10`),
    `10-100` = as.numeric(`10-100`),
    total = `<2.5` + `2.5-10` + `10-100`) -> adsorbed_particles$particle_count
```

```{r}
adsorbed_particles %>%
  purrr::pluck("particle_count") %>%
  dplyr::group_by(site, sp, Rep, face) %>%
  dplyr::summarise(
    `<2.5` = mean(`<2.5`),
    `2.5-10` = mean(`2.5-10`),
    `10-100` = mean(`10-100`),
    total = mean(total)
  ) %>%
  dplyr::ungroup() -> adsorbed_particles$particle_count_micro
```

```{r}
adsorbed_particles %>% 
  purrr::pluck("micro") %>% 
  dplyr::rename(ind = rep) -> adsorbed_particles$micro
```

```{r}
adsorbed_particles %>% 
  purrr::pluck("macro") %>% 
  dplyr::select(-Rq) -> adsorbed_particles$macro
```

```{r}
adsorbed_particles %>% 
  purrr::pluck("micro") %>% 
  dplyr::select(-Sq) -> adsorbed_particles$micro
```
